{ config, pkgs, modulesPath, ... }:

{
  imports =
    [
      # Include the default lxd configuration.
      "${modulesPath}/virtualisation/lxc-container.nix"
      # Include the container-specific autogenerated configuration.
      /etc/nixos/incus.nix
      # Include the OrbStack-specific configuration.
      /etc/nixos/orbstack.nix
      # User added config
      <home-manager/nixos>
      ./global-apps.nix
      ./cah-home.nix
    ];

  users.users.cah = {
    uid = 501;
    extraGroups = [ "wheel" ];

    # simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    group = "users";
    createHome = true;
    home = "/home/cah";
    homeMode = "700";
    shell = pkgs.zsh;
  };

  programs.zsh.enable = true;

  security.sudo.wheelNeedsPassword = false;

  users.mutableUsers = false;

  time.timeZone = "America/New_York";

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  services.tailscale.enable = true;
  services.tailscale.useRoutingFeatures = "both";

  system.stateVersion = "24.11"; # Did you read the comment?
}
